Upgraded pksync to v2.18-1

diff --git a/usr/local/sbin/apt-remove-expired-keys b/usr/local/sbin/apt-remove-expired-keys
--- a/usr/local/sbin/apt-remove-expired-keys
+++ b/usr/local/sbin/apt-remove-expired-keys
@@ -4,9 +4,9 @@
 # descripción         : Eliminar claves públicas de repositorios expiradas
 # autor               : Esteban M. Navas Martín
 # fecha creación      : 10032020
-# última modificación : 10032020
+# última modificación : 27102022
 # uso                 : apt-remove-expired-keys
-# instalación         : Guardar en  /usr/local/sbin/
+# instalación         : Guardar en  /usr/local/sbin/ y asignar permisos de ejecución
 
 #
 # Copyright 2020-2022, Esteban M. Navas Martín <algodelinux@gmail.com>
@@ -23,19 +23,46 @@
 # more details.
 #
 
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-NC='\033[0m' # No Color
+RED='\e[0;31m'
+GREEN='\e[0;32m'
+ORANGE='\e[0;33m'
+YELLOW='\e[1;33m'
+NC='\e[0m' # No Color
 
-if (( $EUID != 0 )); then
-   echo -e "${RED}Please run with SUDO or root user account${NC}"
-   exit 1
+
+# Ensure we're running as root
+if [ "$(id -u)" != 0 ]; then
+        echo -e "${RED}ERROR: This script must run as root.${NC}" 1>&2
+        exit 1
 fi
 
-APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 LC_ALL=C apt-key list |grep -E pub.*expired -A 1 | grep -v -e pub -e -- | sed 's/ //g' > /tmp/removeaptkeys
 
-for key in $(cat /tmp/removeaptkeys); do
-    apt-key del $key
+OLDKEYFILE="/etc/apt/trusted.gpg"
+KEYPATHS="/usr/share/keyrings /etc/apt/keyrings /etc/apt/trusted.gpg.d"
+
+if [ -f $OLDKEYFILE ]; then
+   LC_ALL=C gpg --no-default-keyring --keyring=$OLDKEYFILE --list-keys | grep -E pub.*expired -A 1 > /tmp/expiredkeys
+
+   if [ -s /tmp/expiredkeys ]; then
+      for keyid in $(grep -E [[:xdigit:]]{40} /tmp/expiredkeys | sed 's/^ *//; s/ *$//; /^$/d; /^\s*$/d; s/^\t*//; s/\t*$//;'); do
+          echo -e "${GREEN}Deleting KEY $keyid from $OLDKEYFILE${NC}"
+          gpg --no-default-keyring --keyring=$OLDKEYFILE --batch --yes --delete-keys $keyid
+      done
+   fi
+fi
+
+for KEYPATH in $KEYPATHS; do
+    if [ -d $KEYPATH ] && [ "$(ls -A $KEYPATH)" ]; then
+       for keyfile in $(find $KEYPATH/* -not -name "*~"); do
+           LC_ALL=C gpg --no-default-keyring --keyring=$keyfile --list-keys | grep -E pub.*expired -A 1 > /tmp/expiredkeys
+
+           if [ -s /tmp/expiredkeys ]; then
+              for keyid in $(grep -E [[:xdigit:]]{40} /tmp/expiredkeys | sed 's/^ *//; s/ *$//; /^$/d; /^\s*$/d; s/^\t*//; s/\t*$//;'); do
+                  echo -e "${GREEN}Deleting KEY $keyid from $keyfile${NC}"
+                  gpg --no-default-keyring --keyring=$keyfile --batch --yes --delete-keys $keyid
+              done
+          fi
+       done
+    fi
 done
-
 
