Upgraded pkgsync to v2.18

diff --git a/usr/local/sbin/apt-list-expired-keys b/usr/local/sbin/apt-list-expired-keys
--- a/usr/local/sbin/apt-list-expired-keys
+++ b/usr/local/sbin/apt-list-expired-keys
@@ -4,12 +4,12 @@
 # descripción         : Listar claves públicas de repositorios expiradas
 # autor               : Esteban M. Navas Martín
 # fecha creación      : 10032020
-# última modificación : 10032020
+# última modificación : 27102022
 # uso                 : apt-list-expired-keys
-# instalación         : Guardar en  /usr/local/sbin/
+# instalación         : Guardar en  /usr/local/sbin/ y asignar permisos de ejecución
 
 #
-# Copyright 2020, Esteban M. Navas Martín <algodelinux@gmail.com>
+# Copyright 2020-2022, Esteban M. Navas Martín <algodelinux@gmail.com>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,4 +23,32 @@
 # more details.
 #
 
-APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 LC_ALL=C apt-key list |grep -E pub.*expired -A 1
+RED='\e[0;31m'
+GREEN='\e[0;32m'
+ORANGE='\e[0;33m'
+YELLOW='\e[1;33m'
+NC='\e[0m' # No Color
+
+
+# Ensure we're running as root
+if [ "$(id -u)" != 0 ]; then
+        echo -e "${RED}ERROR: This script must run as root.${NC}" 1>&2
+        exit 1
+fi
+
+
+OLDKEYFILE="/etc/apt/trusted.gpg"
+KEYPATHS="/usr/share/keyrings /etc/apt/keyrings /etc/apt/trusted.gpg.d"
+
+[ -f $OLDKEYFILE ] && echo -e "Checking $OLDKEYFILE" && LC_ALL=C gpg --no-default-keyring --keyring=$OLDKEYFILE --list-keys | grep -E pub.*expired -A 1
+
+for KEYPATH in $KEYPATHS; do
+    if [ -d $KEYPATH ] && [ "$(ls -A $KEYPATH)" ]; then
+       echo -e "\n${ORANGE}[$KEYPATH]${NC}"
+       for keyfile in $(find $KEYPATH/* -not -name "*~"); do
+           echo -e "Checking $keyfile"
+           echo -ne "${RED}"; LC_ALL=C gpg --no-default-keyring --keyring=$keyfile --list-keys | grep -E pub.*expired -A 1; echo -ne "${NC}"
+       done
+    fi
+done
+
