Upgraded pkgsync to v2.27

diff --git a/usr/local/sbin/pkgsync b/usr/local/sbin/pkgsync
--- a/usr/local/sbin/pkgsync
+++ b/usr/local/sbin/pkgsync
@@ -8,7 +8,7 @@
 set -e
 set -o noglob
 export DEBIAN_FRONTEND=noninteractive
-export VERSION=2.25
+export VERSION=2.27
 
 RED='\e[0;31m'
 GREEN='\e[0;32m'
@@ -40,7 +40,7 @@ print_help () {
 	echo "  -g,  --get-keys		exec launchpad-keys to get repositories keys"
 	echo "  -S,  --shutdown		shutdown machine after pkgsync"
 	echo "  -R,  --reboot			reboot machine after pkgsync"
-	echo "  -Rw, --reboot w			reboot machine and boot into windows on EFI computers"
+	echo "  -Rw, --reboot w		reboot machine and boot into windows on EFI computers"
 	echo ""
 	echo "Complete documentation can be found in /usr/share/doc/pkgsync/README.Debian."
 }
@@ -504,6 +504,7 @@ LAUNCHPAD_GETKEYS_PROXY=""
 LAUNCHPAD_GETKEYS_REMOVE_EXPIRED_KEYS=no
 TIMEOUT_FOR_SINC_PUPPET="5"
 TIMEOUT_FOR_DPKG_OR_APT="3m"
+TIMEOUT_FOR_MUSTHAVE_BUILD="2m"
 EFI_DISK=$(mount | grep '/boot/efi' | awk '{print $1}' | sed 's/[0-9]*//g') # Disco que contiene EFI
 ABORT_ON_FAILED_REPOS="yes"
 DISABLED_FAILED_REPOS=false
@@ -532,20 +533,36 @@ BADGER="$!"
 
 trap "kill "${BADGER}" 2>/dev/null || true; lockfile-remove $lockfile; exit" QUIT INT TERM EXIT
 
-if [ ! -r /etc/pkgsync/musthave ]; then
-        IGNORE_MUSTHAVE="yes"
+# Crear el directorio /etc/pkgsync si no existe
+if [ ! -d /etc/pkgsync ]; then
+   echo -e "${GREEN}Creando el directorio /etc/pkgsync ...${NC}"
+   mkdir /etc/pkgsync
 fi
 
-# No ejecutar pkgsync cuando falta alguno de los ficheros musthave, mayhave o maynothave
-if [ ! -r /etc/pkgsync/musthave -a ! "$IGNORE_MUSTHAVE" = "yes" -o \
-     ! -r /etc/pkgsync/mayhave -o \
-     ! -r /etc/pkgsync/maynothave ]; then
-	echo -e "${RED}Error: Missing files in /etc/pkgsync. Aborting.${NC}"
-	echo
-	echo "Please see /usr/share/doc/pkgsync/README.Debian for information on"
-	echo "configuring pkgsync."
+# Crear un fichero /etc/pkgsync/mayhave vacío si no existe
+if [ ! -r /etc/pkgsync/mayhave ]; then
+   echo -e "${GREEN}Creando el fichero /etc/pkgsync/mayhave ...${NC}"
+   touch /etc/pkgsync/mayhave
+fi
 
-	exit 1
+# Crear un fichero /etc/pkgsync/maynothave vacío si no existe
+if [ ! -r /etc/pkgsync/maynothave ]; then
+   echo -e "${GREEN}Creando el fichero /etc/pkgsync/maynothave ...${NC}"
+   touch /etc/pkgsync/maynothave
+fi
+# Generar /etc/pkgsync/musthave si no existe con la lista de paquetes instalados en el sistema
+if [ ! -r /etc/pkgsync/musthave -a ! "$IGNORE_MUSTHAVE" = "yes" ]; then
+   timeout $TIMEOUT_FOR_MUSTHAVE_BUILD /usr/local/sbin/musthave-build
+
+   # Si no se ha creado un fichero musthave, mostramos un error
+   if [ ! -r /etc/pkgsync/musthave ]; then
+   	echo -e "${RED}Error: Fichero musthave no encontrado en /etc/pkgsync. Abortando.${NC}"
+   	echo
+   	echo "Please see /usr/share/doc/pkgsync/README.Debian for information on"
+   	echo "configuring pkgsync."
+
+   	exit 1
+   fi
 fi
 
 # Check if we've got debtags installed
